
name: Release-Docker-Conductor-Tag

on:
  push:
    tags:
      - 'v*'

env:
  HUB: ghcr.io/flowerfine/conductor
  YARN_OPTS: --network-timeout 10000000

jobs:
  release:
    if: github.repository == 'flowerfine/conductor'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Zulu JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Release image
        uses: docker/build-push-action@v5
        with:
          no-cache: false
          cache-from: type=gha
          cache-to: type=gha
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: docker/server/Dockerfile
          build-args: |
            YARN_OPTS=${{ env.HUB }}
          tags: |
            ${{ env.HUB }}/server:${{ github.ref_name }}
